name: Build and deploy the application to Koyeb

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_EXAMPLES_APPS_TOKEN }}"

      - name: Build and deploy the application
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: shiny-python-${{ github.ref_name }}
          service-ports: "8000:http"
          service-routes: "/:8000"
          git-builder: buildpack
          git-run-command: "pip install jupyter && jupyter notebook --ip=0.0.0.0 --port=8000 --allow-root"
          skip-cache: true
